export const appActions = {
  //Authentication
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  SIGN_UP: "SIGN_UP",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  LOGOUT: "LOGOUT",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  RESEND_EMAIL_VERIFICATION: "RESEND_EMAIL_VERIFICATION",
  OPEN_CANDIDATE_LISTS:"OPEN_CANDIDATE_LISTS"
};
